DROP TABLE if EXISTS product_price;
DROP TABLE if EXISTS product_property;
DROP TABLE if EXISTS price;
DROP TABLE if EXISTS property;
DROP TABLE if EXISTS product;

CREATE TABLE product (
    id BIGINT generated BY DEFAULT AS IDENTITY,
    description VARCHAR(255),
    name VARCHAR(255),
    status VARCHAR(255),
    PRIMARY KEY (id)
);

INSERT INTO product (description, name, status) VALUES
    ('a tales of a 1000 and 1 night', 'Book', 'ACTIVE'),
    ('a solid wooden table', 'Table', 'ACTIVE'),
    ('Linkin Park Hybrid Theory', 'Vinyl', 'ACTIVE'),
    ('Jimi Hendrix style', 'Guitar', 'INACTIVE'),
    ('DELL Inspiration model', 'Computer', 'ACTIVE');

CREATE TABLE price (
    id BIGINT generated BY DEFAULT AS IDENTITY,
    effective_date DATE,
    price_value DECIMAL(19,2),
    tax_percentage DECIMAL(19,2),
    PRIMARY KEY (id)
);

INSERT INTO price (effective_date, price_value, tax_percentage) VALUES
    ('20220917', 60.00, 10),
    ('20220916', 500.00, 10),
    ('20220915', 45.00, 23),
    ('20221117', 450.00, 23),
    ('20221117', 5000.00, 23);

CREATE TABLE property (
    id BIGINT generated BY DEFAULT AS IDENTITY,
    property VARCHAR(255),
    property_value VARCHAR(255),
    PRIMARY KEY (id)
);

INSERT INTO property (property, property_value) VALUES
    ('color', 'red'),
    ('color', 'black'),
    ('color', 'orange');

CREATE TABLE product_price (
    product_id bigint NOT NULL,
    price_id bigint NOT NULL,
    CONSTRAINT UK_price_id UNIQUE (price_id),
    CONSTRAINT FK_price_price_id FOREIGN KEY (price_id) REFERENCES price,
    CONSTRAINT FK_price_product_id FOREIGN KEY (product_id) REFERENCES product
);

INSERT INTO product_price (product_id, price_id) VALUES
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5);

CREATE TABLE product_property (
    product_id bigint NOT NULL,
    property_id bigint NOT NULL,
    CONSTRAINT FK_property_id
    FOREIGN KEY (property_id)
    REFERENCES property,
    CONSTRAINT FK_property_product_id
    FOREIGN KEY (product_id)
    REFERENCES product
);

INSERT INTO product_property (product_id, property_id) VALUES
    (1, 1),
    (2, 2),
    (3, 3);